ARG include_tests

FROM ubuntu:18.04 AS include-tests-false
ARG TARGETPLATFORM

ENV ARCHITECTURE=aarch64

RUN apt-get update && apt-get install -y curl
RUN apt-get update && apt-get install -y software-properties-common

# C/C++
RUN apt-get update && apt-get install -y build-essential
RUN apt-get update && add-apt-repository ppa:ubuntu-toolchain-r/test
RUN apt-get update && apt-get install -y gcc-10
RUN apt-get update && apt-get install -y g++-10
RUN apt-get update && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 1
RUN apt-get update && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 1
RUN apt-get update && apt-get install -y flex
RUN apt-get update && apt-get install -y wget

# Install recent version of bison (3.8.2)
RUN set -eux; \
    wget https://ftp.gnu.org/gnu/bison/bison-3.8.2.tar.gz; \
    tar -zxvf bison-3.8.2.tar.gz; \
    cd bison-3.8.2; \
    ./configure; \
    make; \
    make install; \
    ln -s /usr/local/bin/bison /usr/bin/bison; \
    cd ..; \
    rm -rf bison-3.8.2*;

# Java
RUN add-apt-repository -y ppa:openjdk-r/ppa
RUN apt-get install -y ca-certificates-java
RUN apt-get install -y openjdk-17-jdk

# Scala
RUN set -eux; \
    if [ "$TARGETPLATFORM" = "linux/amd64" ]; then ARCHITECTURE=x86_64; elif [ "$TARGETPLATFORM" = "linux/x86_64" ]; then ARCHITECTURE=x86_64; elif [ "$TARGETPLATFORM" = "linux/aarch64" ]; then ARCHITECTURE=aarch64; else ARCHITECTURE=aarch64; fi; \
    curl -fL https://github.com/coursier/launchers/raw/master/cs-${ARCHITECTURE}-pc-linux.gz | gzip -d > cs; \
    chmod +x cs; \
    mv cs /usr/local/bin/cs; \
    cs setup --yes --apps scala,scalac,scala-cli;

# Scala-Bison
RUN set -eux; \
    curl -fL https://gist.githubusercontent.com/phaller/8e7b57c23f80b0ef8b1e68d4eb579dc7/raw/3d5019801e56fb91337b00878df2cae1c7730fa2/scala-bison > scala-bison; \
    chmod +x scala-bison; \
    mv scala-bison /usr/local/bin/scala-bison; \
    curl -fL https://github.com/phaller/scala-bison/releases/download/v1.2/scala-bison-3.3.jar > scala-bison-3.3.jar; \
    mkdir -p /usr/local/share/scala-bison/lib; \
    mv scala-bison-3.3.jar /usr/local/share/scala-bison/lib/scala-bison-3.3.jar;

RUN apt-get update && apt-get install -y software-properties-common
RUN apt-add-repository ppa:fish-shell/release-3
RUN apt-get update && apt-get install -y --no-install-recommends fish

RUN apt-get update && apt-get install -y nasm

RUN adduser --uid 1002 --disabled-password --gecos "" --force-badname student
USER student
WORKDIR /home/student

# Prepare scala-cli (download scala-cli and Scala compiler)
RUN \
  echo "case object Temp" > Temp.scala; \
  cs launch scala-cli -- --power package Temp.scala -o temp; \
  rm temp; \
  cs launch scala-cli:1.5.1 -- --power package Temp.scala -o temp; \
  rm temp; rm Temp.scala;
